name: Test & Publish

on:
  push:
    branches:
      - "master"
  pull_request:
  workflow_dispatch:

concurrency: ${ {github.workflow }}-${{ github.ref }}

jobs:
  Build-Publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
          registry-url: "https://registry.npmjs.org"
      - name: Install
        run: pnpm install
      - name: Typecheck
        run: pnpm run typecheck
      - name: Lint
        run: pnpm run lint
      - name: Test
        run: pnpm run test
      - name: Build
        run: pnpm run build
      - name: Publish
        run: pnpm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_KEY }}
